### ISSUE TITLE
AU Linux kernel 2016 запрос на проверку Задание2 Гарифуллин Шамиль

### ISSUE THREAD

**Issue by esengie** [esengie/au-linux-kernel-spring-2016#1]
https://github.com/esengie/au-linux-kernel-spring-2016/commit/e22211ca4fda02832a824e3266b0f64498b586c9

**Comment by eabatalov** [comment]
You homework should be provided as a single commit.
You've provided the link to not complete homework.

**Comment by eabatalov** [comment]
Almost perfect 95% for the task.
See comments in the commit.
Please always provide your work as a single commit. Everything about it is written on SEWiki.
