### ISSUE TITLE
AU Linux kernel 2016 запрос на проверку КР Гарифуллин Шамиль

### ISSUE THREAD

**Issue by esengie** [esengie/au-linux-kernel-spring-2016#3]
https://github.com/esengie/au-linux-kernel-spring-2016/commit/4fc685263f52047f349c6ea03ed5716ef2bc877e

**Comment by esengie** [comment]
Забыл заассайнить

**Comment by eabatalov** [comment]
Ок. Правильно сделано. 100 баллов из 100.
